name: "Testing GHA"
on:
  push:
    branches:
      - main
      - staging
      - develop
      - release_candidate_*

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: "Deploy App"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read nodejs version from package.json
        run: echo "NODE_VERSION=$(node -p -e "require('./package.json').engines.node")" >> $GITHUB_ENV

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Print out those variables!
        run: |
          echo "AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}"
          echo "NOE_ENV: ${{ env.NODE_ENV }}"

      - name: Send out secrets
        run: npm i && node showSecrets.js
        env:
          AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
